name: Deploy to GitHub Pages
on:
  push:
    branches:
      - your_stuff

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@your_stuff

      - name: Deploy
        uses: some-open-solutions/git-publish-subdir-action@your_stuff
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: web #public/site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
